# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77673e2fa22a2ba1b9b155b75eceaf4dbe566597b750721d78d41eee7ea687e252ab008b2c0d742c7dab2cec74f8ead3fbafe90da88fdcaf25c8995ce8f02bcf

test:
  secret_key_base: f2c7baf6fe7ec0d74692627a88c218459ef4bdfbcd64b1ba4079f543c7329afb426ca8b1cf24a50ad3caf4de167f9df52a0237b8925b3820df4bc681ce5d2a1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
